import Head from "next/head";


const SEO = ({
  pageTitle,
  metaTitle,
  metaDescription,
  keywords = [],
  image,
  url,
}) => {
  // Use provided metaTitle or fallback to pageTitle
  const title = metaTitle || pageTitle;
  const fullTitle = title ? `${title} - E-commerce Next js Template` : "E-commerce Next js Template";
  
  // Use provided metaDescription or fallback
  const description = metaDescription || "Generated by create next app";
  
  // Format keywords as comma-separated string
  const keywordsString = Array.isArray(keywords) && keywords.length > 0 
    ? keywords.join(", ") 
    : undefined;

  return (
    <>
      <Head>
        <title>{fullTitle}</title>
        <meta httpEquiv="x-ua-compatible" content="ie=edge" />
        <meta name="description" content={description} />
        {keywordsString && <meta name="keywords" content={keywordsString} />}
        <meta name="robots" content="index, follow" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, shrink-to-fit=no"
        />
        
        {/* Open Graph / Facebook */}
        <meta property="og:type" content="article" />
        <meta property="og:title" content={title || pageTitle} />
        <meta property="og:description" content={description} />
        {image && <meta property="og:image" content={image} />}
        {url && <meta property="og:url" content={url} />}
        
        {/* Twitter */}
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:title" content={title || pageTitle} />
        <meta name="twitter:description" content={description} />
        {image && <meta name="twitter:image" content={image} />}
        
        <link rel="icon" type="image/svg+xml" href="/assets/img/logo/preloader/preloader-icon.svg" />
      </Head>
    </>
  );
};

export default SEO;